language: generic

sudo: required
services:
  - docker
  
before_install:
  - docker build  -t englugun/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true englugun/docker-react npm run test
  